# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 05:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bedrooms', models.PositiveIntegerField()),
                ('suite_number', models.PositiveIntegerField(unique=True)),
                ('max_occupants', models.PositiveIntegerField()),
                ('lease_term', models.PositiveIntegerField()),
                ('maximum_income', models.PositiveIntegerField()),
                ('minimum_income', models.PositiveIntegerField()),
                ('rent', models.PositiveIntegerField()),
                ('bus_transit', models.CharField(choices=[(b'Great', b'Great'), (b'Fair', b'Fair'), (b'Poor', b'Poor')], max_length=20)),
                ('rail_transit', models.CharField(choices=[(b'Great', b'Great'), (b'Fair', b'Fair'), (b'Poor', b'Poor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('street_address', models.CharField(max_length=200, unique=True)),
                ('single_unit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentComplexUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.ApartmentComplex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('apartment_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.ApartmentComplex')),
            ],
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='apartment_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.ApartmentComplex'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.ApartmentBuilding'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.ApartmentContact'),
        ),
        migrations.AlterUniqueTogether(
            name='apartmentcontact',
            unique_together=set([('phone', 'apartment_complex')]),
        ),
        migrations.AlterUniqueTogether(
            name='apartmentbuilding',
            unique_together=set([('name', 'apartment_complex')]),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set([('building', 'suite_number')]),
        ),
    ]
