# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentcomplex',
            options={'verbose_name_plural': 'apartment complexes'},
        ),
    ]
